name: dna-quantum
channels: 
        - conda-forge
dependencies:
        - pip
        - python=3.10
        - pip:
          - jupyterlab
          - matplotlib
          - numpy
          - qiskit==1.0.0
          - pylatexenc
          - qiskit-aer
